# Generated by Django 4.2.6 on 2023-10-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('numero_documento', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.personas')),
            ],
        ),
    ]
