# Generated by Django 4.2.6 on 2023-10-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_alter_email_persona_id_alter_telefono_persona_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='persona_id',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='telefono',
            old_name='persona_id',
            new_name='persona',
        ),
    ]
